### ISSUE TITLE
Assume sync if no promise is returned?

### ISSUE THREAD

**Issue by ericelliott** [spion/blue-tape#11]
If the test return value is not a promise, would it be better to assume that the test is synchronous?

**Comment by spion** [comment]
Might be, but in that case, callbacks will not be supported. That will result with valid tape tests not being valid blue-tape tests.

**Comment by ericelliott** [comment]
I think I'd prefer to see blue go its own way and break compatibility with tape.

Ideally:

```
import tape from 'tape'; // for old tests
import test from 'blue-tape'; // new hotness

test('name', (assert) => new Promise(resolve => {
  assert.pass('something');
  resolve();
}));

test('synchronous', (assert) => {
  assert.pass('something');
  // no need for `resolve()` or `assert.end()`
});

// Tape tests are fine...
tape('name', (assert) => {
  assert.pass('something else');
  assert.end();
});
```

**Comment by spion** [comment]
That wont quite work: you wont be able to nest tests of a different kind.

**Comment by ericelliott** [comment]
> That wont quite work: you wont be able to nest tests of a different kind

Why would you want to do that instead of this?:

```js
blue('name', assert => {
  assert.test('nested', assert => {
    // can return promise here
  })
})
```
> plus I'm not sure how success/failure/etc counts will work given that there would be two separate instances of tape

```js
import test from 'blue-tape';

const tape = test.tape(); // return canonical instance.
```

**Comment by spion** [comment]
for # 1, because you might want to have both callback and promise tests nested within a single item

for # 2, blue-tape modifies a prototype from the original tape, so the original is not available anymore

**Comment by ericelliott** [comment]
> for # 1, because you might want to have both callback and promise tests nested within a single item

1. Doesn't `blue-tape` still support old tape callbacks now?
2. Why would you want both in one item? Wouldn't it make more sense for one test to remain self consistent?

> for # 2, blue-tape modifies a prototype method from the original tape (Test.prototype.run), so the original is not available anymore

Save it and return an unmodified tape?

**Comment by ericelliott** [comment]
Maybe it's better the way it is, anyway. =)

**Comment by spion** [comment]
@ericelliott yes it does, but if we assume that tests which don't return promises are sync, then it will stop supporting them.

I do think it would be cool to do a promise-only test tool. One that creates tap output and doesn't require a separate runner that defines a bunch of global functions to provide a DSL feel. Might give it a try...

**Comment by ericelliott** [comment]
:+1:
