### ISSUE TITLE
Move tape to peer dependencies

### ISSUE THREAD

**Issue by 11bit** [spion/blue-tape#17]
I am trying to run blue-tape tests in gulp with gulp-tape plugin. But unfortunately this plugin assumes that tape is installed. I see two solutions for this issue. One is just to fork  gulp-tape and make it work with blue-tape. But it doesn't look very nice. The other way is modify blue-tape deps - move tape from dependencies to peerDependencies. I am not sure if this is a right way but it will give an opportunity to use blue-tape in conjunction with other tape-related libraries without forcing them to know about blue-tape.
I want to ask your opinion if it makes any sense. Or maybe there are better solutions?

**Comment by spion** [comment]
I think gulp-tape is doing the wrong thing here - the right thing would be to simply run the tests as a process and get that process stdout/stderr.

However, if you insist on the gulp way (a clone of the grunt way) of doing things, I think the sensible way forward here would be to make tape injectable via options in `gulp-tape`

```js
var tape = opts.tape || require('tape')
```

**Comment by 11bit** [comment]
Thanks for advice. I will try to do this way. 
But regardless of gulp-tape doing it right or wrong , from conceptual standpoint don't you think that tape here should be in peer dependencies because blue-tape acts as a plugin?

**Comment by spion** [comment]
From a user standpoint, `blue-tape` is a replacement, not a plugin. The fact that its internally implemented by using tape and overriding its methods doesn't affect that.

**Comment by 11bit** [comment]
I see. Thanks
