### ISSUE TITLE
Using with t.plan and t.end

### ISSUE THREAD

**Issue by olalonde** [spion/blue-tape#24]
I was wondering if it was possible to use blue-tape with `t.plan` and `t.end` as not all my tests return promises. I've tried t.plan but getting an error:

```
not ok 2 plan != count
  ---
    operator: fail
    expected: 5
    actual:   0
  ...
```

**Comment by oncletom** [comment]
Agreed, it would avoid wrapping tests in promises when testing a few async-non-promise methods.

**Comment by spion** [comment]
You only need plan for the non-promise tests.
