### ISSUE TITLE
Test that promise rejects/throws

### ISSUE THREAD

**Issue by whitelizard** [spion/blue-tape#30]
I can't figure out how I should test that a function that returns a promise (async function) rejects/throws.

I feel I have tried everything up my sleeve: async-await vs then-catch, t.throws(), catch inside test and t.ok()/t.end(), transpiling with babel vs babel-node, etc.

How?

**Comment by aluanhaddad** [comment]
The `README` states that blue-tape
> Also provides t.shouldFail(promise P, optional class|regex expected, optional message) (as well as the alias shouldReject) which returns a new promise that resolves successfully if P rejects. If you provide the optional class, or regex then it additionally ensures that err is an instance of that class or that the message matches the regular expression. The behaviour is identical to tape's throws assertion.

**Comment by whitelizard** [comment]
Sorry, this was actually an error in the code that was tested
