### ISSUE TITLE
Adding Generator Support?

### ISSUE THREAD

**Issue by wavded** [spion/blue-tape#6]
@spion just a thought to throw your way to get your thoughts.  If a user passes a generator function for a test, wrap it in a `Promise.coroutine` call (or something like that) in order to `yield` promises, etc.  Here is an implementation I'm using currently that wraps blue-tape.

```js
import test from 'blue-tape'
import Promise from 'bluebird'

export default function genTest (...args) {
  let testArgs = args.map( arg => {
    if (arg && arg.constructor.name === 'GeneratorFunction') {
      return Promise.coroutine(arg)
    }

    return arg
  })
  test.apply(null, testArgs)
}
```

Allowing tests like so:

```js
test('User#save', function* (t) {
  let user = common.initUser()
  user.password = 'foo'
  yield user.save()
  console.log(user.password)
})
```

Thoughts?

**Comment by spion** [comment]
I think its pretty great :) Two thoughts:

* ES7 (as in babel) async functions will work out of the box, right?
* is there any other sensible way to interpret a generator being passed to the function? A generator that yields tests doesn't seem to make much sense, so I'm assuming no...

**Comment by wavded** [comment]
1. I tried it in Babel and didn't have any luck.
2. There are checks for generator support (like [this](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/es6/generators.js)), but in terms of checking if a function is a generator, this was the best I've found so far.  Bluebird checks for any function: https://github.com/petkaantonov/bluebird/blob/734a16f437f23d66e4bbe9ae51668589f91f940d/src/generators.js#L136

**Comment by wavded** [comment]
Found this as well: https://github.com/blakeembrey/is-generator/blob/master/is-generator.js

**Comment by getify** [comment]
What would your `test(..)` utility do if you passed a function that wasn't a generator, but still provided an iterator that could run its steps one at a time, as if it *was* a generator?

You seem to actively be saying "we would only want special handling for a generator and not for an iterator-returning function that acts like a generator." Why would you want to discriminate?

**Comment by spion** [comment]
Re 1, No luck as in this didn't work?

```js
t.test('name', async function {
  var x = await blah();
  return y(x)
});
```

Re 2, I didn't mean that, I meant like is there any other way in which a generator could be used as an argument except as a promise-yielding generators. Probably not, so the only interpretation that makes sense is this one

**Comment by getify** [comment]
BTW: what I'm suggesting isn't theoretical... any "task queue" that exposes itself as an iterator would fit my description.

Moreover, I have created an abstraction in my [asynquence](http://github.com/getify/asynquence) library called ["iterable sequences"](https://github.com/getify/asynquence#iterable-sequences), which is essentially an imperative way to create the same kind of step-by-step behavior as a generator, exposed as a normal standard iterator. Consider:

```js
function testCase(..) {
   return ASQ.iterable()
      .then( doStep1 )
      .then( doStep2 )
      .then( doStep3 );
}
```

If you execute `testCase(..)`, you get back an *iterable sequence*, which is an iterable/iterator that can be iterated identically to a normal generator's iterator (including whatever promise wrapping might be appropriate as in your OP).

I personally would want to be able to pass such a `testCase(..)` function to your lib and get the same special behavior as passing the equivalent generator. Your library shouldn't care to distinguish between the two, right?

**Comment by wavded** [comment]
Re 1: I can't seem to get that to work, parse errors in Babel, can async funcs be passed in anonymously like that?

Re 2: I can't see it being used in another way at this time.

**Comment by spion** [comment]
getify, why would you need that? you could just use a function that returns a promise for the last step...

**Comment by wavded** [comment]
I may have Babel misconfigured... I'll run a few tests in a bit... noticed this as well http://babeljs.io/docs/usage/transformers/other/bluebird-coroutines

**Comment by getify** [comment]
The point is not "why would you need that' but "that these things can and do exist". Could any existing code be refactored so it fit with this lib's decisions? Sure.

But the point I'm making is that distinguishing between a generator and a normal function that acts externally (iterator-wise) **just like a generator** is hostile and counter-intuitive.

**Comment by spion** [comment]
@getify I see the point. What should I do if the iterable doesn't generate a promise?

**Comment by getify** [comment]
If you want to support special behavior around iterator-producing-functions (wrapping them in a promise), whether that be a real generator or just a function that acts like one, I think you need to have an explicit API for it and not use the magical detection logic.

One quick example thought:

```js
test( { iterable: function*() { .. } } );

test( { iterable: function(){ .. return it; } } );
```

That is, for someone to signal to the lib that they're passing a "thing-that-when-executed-will-produce-a-generator-that-i-want-you-to-promise-wrap", they signal it by passing an object with an `iterable` property holding reference to said function. That should be an easy thing for the lib to test for and handle appropriately.

**Comment by wavded** [comment]
I personally don't mind the magic, this lib gifts tape with promise support (that's it), whether that comes from an generator or otherwise.  This particular use of generators is common (co, koa, bluebird, when.js, Q come to mind).  However, if there isn't a standard way to detect generators, perhaps we make it more explicit by having keeping `test` how it is currently is and having like test.co(function*()) specifically for that `Promise.coroutine` behavior?  I guess I'm not seeing how other types of iterables would make sense in this context (tape).

**Comment by spion** [comment]
@getify hmm. I think the code can just expect the iterable to produce promises and complain if thats not the case. If it makes sense to support other kinds of values it can always be added at a later time.

**Comment by getify** [comment]
@waved any generator that you could write that would be sensible here, could have been substituted with a transpiled version (aka, the function/closure/switch dance) into a normal function that returns a standard iterator. Moreover, I could manually write a state machine in that same style. Or I could choose to write it using the asynquence iterable-sequence style. Those are all isomorphic to a generator. IMO makes no sense to bless the use of generator and discriminate against all those others.

@spion yeah, you can opt not to add any magical sugar. but a generator's iterator, nor any of the other types I'm suggesting, will produce such a promise. Instead, users will have to manually wrap, like this (with asynquence):

```js
test( "..",  ASQ().runner(function*() { .. }).toPromise() );
```

Or any of the other major promise/async libs that provide `spawn(..)` or `run(..)` or the like. Forcing the user to manually wrap is fine. The OP wanted magic. I can see why magic is nice. All I was arguing is, if you're going to have magic, have it fairly for all the kids. ;-)

**Comment by wavded** [comment]
@getify agreed, I think those use cases within the `tape` context would need to vetted out more and as @spion stated, could be added later.

**Comment by spion** [comment]
What I meant is blue-tape could add just one more case in addition to value.then


```js
if (checkPromise(p)) {
...
}
else if (checkIterable(p)) {
  runIterableOfPromises(p).then(_ => self.end, e => { self.error(e); self.end() })
}
```

**Comment by getify** [comment]
@wavded "added later" is necessarily going to either require breaking-change refactoring (from implicit magic to explicit)... OR you're going to have forked magic, where it works one way for iterators and entirely differently for everything else.

Not my lib obviously, but I would absolutely detest either of those as possible/likely futures, and avoid even one foot down such a road if I could even remotely imagine it happening.

Anyway, I've said my peace. I won't bother you all anymore. :)

**Comment by getify** [comment]
@spion sure, but `checkIterable(p)` if `p` is a generator is not going to work... a generator is not an iterable, it has to be run to produce an iterable.

**Comment by spion** [comment]
@getify duh, of course - I know that :) At that point in the code the test function has already been called - thats why I used the name `checkIterable`

**Comment by getify** [comment]
oh, ok, my mistake. I shouldn't have been speaking without more fully understanding the code in the lib. I was only going off the impressions left by the initial OP. <shuts up> :)

**Comment by spion** [comment]
yeah I was only wondering what to do if the iterable produces something that is not a promise - and the only thing I come up with for now is throwing an error that thats not supported.

**Comment by wavded** [comment]
Good points @getify, makes sense. @spion I'm on board with future proofing and throwing an error for now if the iterable does not produce a promise.

**Comment by wavded** [comment]
@spion https://github.com/rektide/co-tape :)

**Comment by spion** [comment]
Closing this as I don't think its right to narrowly interpret a general concept such as generators and iterators in such a special way (generators may be more apt for property testing instead), and because async functions are clearly the way to go here.
